<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
    <title>Native PHP template engine</title>
</head>
<body>
<div class="wrapper">
    <div class="content">
        <?= $this->getSection('content') ?>
        <div class="clear clearfix"></div>
    </div>
</div>
<div class="footer">
    <?= $this->getSection('footer') ?>
</div>
</body>
</html>
